---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# NOTE: The Packit copr_build tasks help to check if every commit builds on
# supported Fedora and CentOS Stream arches.
# They do not block the current Cirrus-based workflow.

downstream_package_name: skopeo
upstream_tag_template: v{version}

specfile_path: skopeo.spec

# Disable automatic merging for Copr builds (and subsequent Testing Farm)
merge_pr_in_ci: false

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: true
    targets:
      - epel-10-x86_64

